# Generated by Django 4.1.2 on 2022-10-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=9, verbose_name='Latitud')),
                ('longitude', models.CharField(max_length=9, verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Coordenadas',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Conductor',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('day', models.DateField(verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de Finalización')),
                ('destination_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_point', to='schedule.coordinates', verbose_name='Lugar de Destino')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.driver', verbose_name='Conductor')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_point', to='schedule.coordinates', verbose_name='Lugar de Recogida')),
            ],
            options={
                'verbose_name': 'Pedido',
            },
        ),
    ]
